### ISSUE TITLE
Relay chain Mock verification

### ISSUE THREAD

**Issue by DZahar0v** [mixbytes/lido-dot-ksm#74]
Verify that the Relay chain staking pallet mock implementation in the test was implemented correctly.
Relay chain mock https://github.com/mixbytes/lido-dot-ksm/blob/main/tests/helpers.py
Staking pallet code https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs
Result of verification - each line of code in Mock should be linked to code in staking pallet

**Comment by karapetyantv** [comment]
Closing. Moved to Asana
