### ISSUE TITLE
MethodID for 0x79292235

### ISSUE THREAD

**Issue by mkchungs** [mixbytes/lido-dot-ksm#92]
Hello Lido team,

Can you please provide the abi for function `0x79292235`?  we would like to decode txIntput for xcm/staking transaction like this: https://polkaholic.io/tx/0x6d3894798e40bc9f7727caa7db9c3f6f2b6996bbdb446d442ffde17a5c64b16f

I've compiled the current master branch and load all the available abi into our database but there's no exact match for `0x79292235`. Is there any other branch I should look at?

**Comment by DZahar0v** [comment]
Hello! Sorry for so long delay( It is `reportRelay()` function from OracleMaster contract (here is the link https://github.com/mixbytes/lido-dot-ksm/blob/main/contracts/OracleMaster.sol#L255-L275)
